apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: helm
version: 0.1.0
dependencies:
  - name: nats
    version: 0.15.0
    repository: https://nats-io.github.io/k8s/helm/charts/
    condition: cluster.create
